// <auto-generated />
using System;
using MatriculaCMP.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatriculaCMP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129211824_AddAceptaPoliticasPrivacidad")]
    partial class AddAceptaPoliticasPrivacidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatriculaCMP.Shared.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.ConsejoRegional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsejoRegionales");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Correlativos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Correlativos");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Diploma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroColegiatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("RutaPdf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaPdfFirmado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("Diplomas");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Educacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsExtranjera")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEmisionTitulo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReconocimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevalidacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUniversidadExtranjera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisUniversidadId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("ResolucionPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoValidacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UniversidadId")
                        .HasColumnType("int");

                    b.Property<string>("UniversidadOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UniversidadPeruanaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UniversidadId");

                    b.ToTable("Educaciones");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.EducacionDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarnetExtranjeriaPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificadoAntecedentesPenalesPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstanciaInscripcionReconocimientoSuneduPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstanciaInscripcionRevalidacionUniversidadNacionalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstanciaInscripcionSuneduPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducacionId")
                        .HasColumnType("int");

                    b.Property<string>("ReconocimientoSuneduPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevalidacionUniversidadNacionalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloMedicoCirujanoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducacionId")
                        .IsUnique();

                    b.ToTable("EducacionDocumentos");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.EstadoCivil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoCiviles");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VerReporte")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EstadoSolicitudes");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.GrupoSanguineo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrupoSanguineos");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.MaestroRegistro", b =>
                {
                    b.Property<int>("MaestroRegistro_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaestroRegistro_Key"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaestroTabla_Key")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaestroRegistro_Key");

                    b.ToTable("MaestroRegistro", (string)null);
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Mat_ConsejoRegional", b =>
                {
                    b.Property<int>("ConsejoRegional_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsejoRegional_Key"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConsejoRegional_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EsConsejoNacional")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAbreviado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ubigeo_Key")
                        .HasColumnType("int");

                    b.HasKey("ConsejoRegional_Key");

                    b.ToTable("Mat_ConsejoRegional", (string)null);
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Mat_Pais", b =>
                {
                    b.Property<int>("Pais_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pais_key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pais_key"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("bActivo");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Iso3");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("Pais_key");

                    b.ToTable("Mat_Pais", (string)null);
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Mat_Ubigeo", b =>
                {
                    b.Property<int>("UbigeoKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ubigeo_Key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbigeoKey"));

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CodigoPostal");

                    b.Property<string>("DepartamentoId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Departamento_Id");

                    b.Property<string>("DistritoId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Distrito_Id");

                    b.Property<bool?>("EsExtranjero")
                        .HasColumnType("bit")
                        .HasColumnName("EsExtranjero");

                    b.Property<bool?>("FlgActivo")
                        .HasColumnType("bit")
                        .HasColumnName("flg_activo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("NombreUnido")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("NombreUnido");

                    b.Property<string>("ProvinciaId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Provincia_Id");

                    b.Property<string>("UbigeoId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("Ubigeo_Id");

                    b.Property<string>("UbigeoIneiId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("UbigeoInei_Id");

                    b.Property<string>("UbigeoMundialId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("UbigeoMundial_Id");

                    b.HasKey("UbigeoKey");

                    b.ToTable("Mat_Ubigeo", (string)null);
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuloIcono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.PerfilMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("PerfilId");

                    b.ToTable("PerfilMenu");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConsejoRegionalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartamentoDomicilioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartamentoNacimientoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionVia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescripcionZona")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DistritoDomicilioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistritoNacimientoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoCivilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupoSanguineoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroColegiatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaisNacimientoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaDomicilioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaNacimientoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Sexo")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoDocumentoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViaDomicilioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaDomicilioId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoSanguineoId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaPoliticasPrivacidad")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("DDJJFirmadaIdPeru")
                        .HasColumnType("bit");

                    b.Property<string>("DocumentoFirmanteDDJJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoSolicitudId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFirmaDDJJ")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("RutaDDJJFirmada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("EstadoSolicitudId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.SolicitudHistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstadoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCambio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudHistorialEstados");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumentos");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Ubigeo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPadre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ubigeos");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Universidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Universidades");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.ViaDomicilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViaDomicilios");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.ZonaDomicilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZonaDomicilios");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Diploma", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatriculaCMP.Shared.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Educacion", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.Persona", "Persona")
                        .WithMany("Educaciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatriculaCMP.Shared.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId");

                    b.Navigation("Persona");

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.EducacionDocumento", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.Educacion", "Educacion")
                        .WithOne("Documento")
                        .HasForeignKey("MatriculaCMP.Shared.EducacionDocumento", "EducacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Educacion");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.PerfilMenu", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatriculaCMP.Shared.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Persona", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.MaestroRegistro", "GrupoSanguineo")
                        .WithMany()
                        .HasForeignKey("GrupoSanguineoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoSanguineo");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Solicitud", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.Area", "Area")
                        .WithMany("Solicitudes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MatriculaCMP.Shared.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("EstadoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatriculaCMP.Shared.Persona", "Persona")
                        .WithMany("Solicitudes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.SolicitudHistorialEstado", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.EstadoSolicitud", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId");

                    b.HasOne("MatriculaCMP.Shared.EstadoSolicitud", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatriculaCMP.Shared.Solicitud", "Solicitud")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Universidad", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.Pais", "Pais")
                        .WithMany("Universidades")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Usuario", b =>
                {
                    b.HasOne("MatriculaCMP.Shared.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatriculaCMP.Shared.Persona", "Persona")
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonaId");

                    b.Navigation("Perfil");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Area", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Educacion", b =>
                {
                    b.Navigation("Documento");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.EstadoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Pais", b =>
                {
                    b.Navigation("Universidades");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Persona", b =>
                {
                    b.Navigation("Educaciones");

                    b.Navigation("Solicitudes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MatriculaCMP.Shared.Solicitud", b =>
                {
                    b.Navigation("HistorialEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
